on: 'pull_request'

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Setup
        uses: actions/setup-node
        with:
          node-version: '12'
      - name: Instala dependências
        run: npm i
      - name: Roda ESlint
        run: npx eslint